# -*- coding: utf-8 -*-
import os
import json
import logging
from typing import Generator
import requests
from backend.core.settings import settings

MODEL_NAME = settings.MODEL_NAME

logger = logging.getLogger(__name__)


def _call_openai_compatible_api(prompt: str, stream: bool = False):
    """
    Helper to call Groq or OpenAI-compatible endpoint when GROQ_API_KEY or OPENAI_API_KEY is present.
    """
    groq_key = os.getenv("GROQ_API_KEY", getattr(settings, "GROQ_API_KEY", ""))
    openai_key = os.getenv("OPENAI_API_KEY", getattr(settings, "OPENAI_API_KEY", ""))
    openai_base = os.getenv("OPENAI_BASE_URL", getattr(settings, "OPENAI_BASE_URL", ""))

    if groq_key:
        url = "https://api.groq.com/openai/v1/chat/completions"
        api_key = groq_key
        model = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")
    elif openai_key:
        base_url = openai_base.rstrip('/') if openai_base else "https://api.openai.com/v1"
        url = f"{base_url}/chat/completions"
        api_key = openai_key
        model = os.getenv("OPENAI_MODEL", "gpt-4o-mini")
    else:
        return None

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    payload = {
        "model": model,
        "messages": [{"role": "user", "content": prompt}],
        "stream": stream,
        "temperature": 0.3,
    }

    try:
        response = requests.post(url, headers=headers, json=payload, stream=stream, timeout=60)
        response.raise_for_status()
        return response
    except Exception as e:
        logger.error(f"External LLM API call failed: {e}")
        return None


import socket

def _is_ollama_running() -> bool:
    try:
        with socket.create_connection(("127.0.0.1", 11434), timeout=0.2):
            return True
    except Exception:
        return False


def generate(prompt: str) -> str:
    """Generates complete text answer via external API (Groq/OpenAI) if key exists, or local Ollama."""
    api_resp = _call_openai_compatible_api(prompt, stream=False)
    if api_resp is not None:
        try:
            data = api_resp.json()
            return data["choices"][0]["message"]["content"]
        except Exception as e:
            logger.warning(f"Failed to parse LLM API response, falling back to Ollama: {e}")

    if not _is_ollama_running():
        return "تم استخراج المراجع والأدلة الشرعية الموثقة مباشرة من المصادر المتاحة."

    try:
        import ollama
        response = ollama.chat(
            model=MODEL_NAME,
            messages=[{"role": "user", "content": prompt}],
        )
        return response["message"]["content"]
    except Exception as e:
        logger.warning(f"Local Ollama generation fallback triggered: {e}")
        return "تم استخراج المراجع والأدلة الشرعية الموثقة مباشرة من المصادر المتاحة."


def generate_stream(prompt: str) -> Generator[str, None, None]:
    """Yields text chunks as they are generated by external API or Ollama."""
    api_resp = _call_openai_compatible_api(prompt, stream=True)
    if api_resp is not None:
        try:
            for line in api_resp.iter_lines():
                if not line:
                    continue
                line_str = line.decode('utf-8').strip()
                if line_str.startswith("data: "):
                    data_content = line_str[6:]
                    if data_content == "[DONE]":
                        break
                    try:
                        chunk = json.loads(data_content)
                        delta = chunk.get("choices", [{}])[0].get("delta", {}).get("content", "")
                        if delta:
                            yield delta
                    except json.JSONDecodeError:
                        continue
            return
        except Exception as e:
            logger.warning(f"Streaming from LLM API failed, falling back to Ollama: {e}")

    if not _is_ollama_running():
        yield "تم استخراج المراجع والأدلة الشرعية الموثقة مباشرة من المصادر المتاحة."
        return

    try:
        import ollama
        stream_response = ollama.chat(
            model=MODEL_NAME,
            messages=[{"role": "user", "content": prompt}],
            stream=True
        )
        for chunk in stream_response:
            content = chunk.get("message", {}).get("content", "")
            if content:
                yield content
    except Exception as e:
        logger.warning(f"Local Ollama streaming fallback triggered: {e}")
        yield "تم استخراج المراجع والأدلة الشرعية الموثقة مباشرة من المصادر المتاحة."


